In [1]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, matthews_corrcoef, cohen_kappa_score
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

def create_dataset(n_samples, class_sep, weights):
    X, y = make_classification(n_samples=n_samples, n_features=2, n_redundant=0, n_informative=2,
                               n_clusters_per_class=1, class_sep=class_sep, weights=weights, random_state=42)
    return train_test_split(X, y, test_size=0.3, random_state=42)

def evaluate_metrics(y_true, y_pred, y_prob):
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    auc_roc = roc_auc_score(y_true, y_prob)
    mcc = matthews_corrcoef(y_true, y_pred)
    kappa = cohen_kappa_score(y_true, y_pred)
    
    cm = confusion_matrix(y_true, y_pred)
    
    return {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "AUC-ROC": auc_roc,
        "MCC": mcc,
        "Cohen's Kappa": kappa,
        "Confusion Matrix": cm
    }

def print_results(dataset_name, metrics):
    print(f"\n{dataset_name}:")
    for metric, value in metrics.items():
        if metric != "Confusion Matrix":
            print(f"{metric}: {value:.4f}")
        else:
            print(f"{metric}:\n{value}")

# Create and evaluate different datasets
datasets = [
    ("Balanced Dataset", 1000, 2.0, [0.5, 0.5]),
    ("Imbalanced Dataset", 1000, 2.0, [0.9, 0.1]),
    ("Noisy Dataset", 1000, 0.5, [0.5, 0.5]),
]

for name, n_samples, class_sep, weights in datasets:
    X_train, X_test, y_train, y_test = create_dataset(n_samples, class_sep, weights)
    
    model = LogisticRegression()
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]
    
    metrics = evaluate_metrics(y_test, y_pred, y_prob)
    print_results(name, metrics)


Balanced Dataset:
Accuracy: 0.9967
Precision: 0.9935
Recall: 1.0000
F1 Score: 0.9967
AUC-ROC: 0.9950
MCC: 0.9934
Cohen's Kappa: 0.9933
Confusion Matrix:
[[146   1]
 [  0 153]]

Imbalanced Dataset:
Accuracy: 0.9967
Precision: 1.0000
Recall: 0.9730
F1 Score: 0.9863
AUC-ROC: 1.0000
MCC: 0.9845
Cohen's Kappa: 0.9844
Confusion Matrix:
[[263   0]
 [  1  36]]

Noisy Dataset:
Accuracy: 0.7200
Precision: 0.7594
Recall: 0.6601
F1 Score: 0.7063
AUC-ROC: 0.7720
MCC: 0.4452
Cohen's Kappa: 0.4413
Confusion Matrix:
[[115  32]
 [ 52 101]]
